version: "3.7"
services:
  web:
    container_name: delivery-fix-user-ms
    build: .
    ports:
      - "4572:4572"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"