/*
 * This file is generated by jOOQ.
 */
package com.revolut.test.backend.accountWs.database.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.processing.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = 1542161307;

    private String   id;
    private String   ownerName;
    private UInteger currency;
    private Integer  balance;
    private Date     balanceLastUpdate;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.ownerName = value.ownerName;
        this.currency = value.currency;
        this.balance = value.balance;
        this.balanceLastUpdate = value.balanceLastUpdate;
    }

    public Account(
        String   id,
        String   ownerName,
        UInteger currency,
        Integer  balance,
        Date     balanceLastUpdate
    ) {
        this.id = id;
        this.ownerName = ownerName;
        this.currency = currency;
        this.balance = balance;
        this.balanceLastUpdate = balanceLastUpdate;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getOwnerName() {
        return this.ownerName;
    }

    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    public UInteger getCurrency() {
        return this.currency;
    }

    public void setCurrency(UInteger currency) {
        this.currency = currency;
    }

    public Integer getBalance() {
        return this.balance;
    }

    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    public Date getBalanceLastUpdate() {
        return this.balanceLastUpdate;
    }

    public void setBalanceLastUpdate(Date balanceLastUpdate) {
        this.balanceLastUpdate = balanceLastUpdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(ownerName);
        sb.append(", ").append(currency);
        sb.append(", ").append(balance);
        sb.append(", ").append(balanceLastUpdate);

        sb.append(")");
        return sb.toString();
    }
}
