/*
 * This file is generated by jOOQ.
 */
package com.revolut.test.backend.accountWs.database;


import com.revolut.test.backend.accountWs.database.tables.Account;
import com.revolut.test.backend.accountWs.database.tables.FlywaySchemaHistory;
import com.revolut.test.backend.accountWs.database.tables.Operation;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1796240730;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>account</code>.
     */
    public final Account ACCOUNT = com.revolut.test.backend.accountWs.database.tables.Account.ACCOUNT;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.revolut.test.backend.accountWs.database.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>operation</code>.
     */
    public final Operation OPERATION = com.revolut.test.backend.accountWs.database.tables.Operation.OPERATION;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Operation.OPERATION);
    }
}
