/*
 * This file is generated by jOOQ.
 */
package com.revolut.test.backend.accountWs.database;


import com.revolut.test.backend.accountWs.database.tables.Account;
import com.revolut.test.backend.accountWs.database.tables.FlywaySchemaHistory;
import com.revolut.test.backend.accountWs.database.tables.Operation;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>operation</code>.
     */
    public static final Operation OPERATION = Operation.OPERATION;
}
